---
version: '2'
services:
  broker:
    image: alpine-kafka:1.1.0-03
    environment:
      ADVERTISE_PUB_IP: 'false'
      JVMFLAGS: -Xmx1024m -Xms1024m
      KAFKA_ADVERTISE_PORT: '9092'
      KAFKA_AUTO_CREATE_TOPICS: 'true'
      KAFKA_DELETE_TOPICS: 'false'
      KAFKA_LOG_RETENTION_HOURS: '120'
      KAFKA_NUM_PARTITIONS: '3'
      KAFKA_OFFSET_RETENTION_MINUTES: '10080'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '3'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '3'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '3'
      # Use rancher dns for service discovery
      KAFKA_ZOOKEEPER_CONNECT: 'zk.zookeeper'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://:9092'
    volumes:
      - /srv/kafka/data:/var/lib/kafka:rw
      - /srv/kafka/logs:/var/log/kafka:rw
    external_links:
      - zookeeper/zk:zk
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: kafka=1
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=kafka/broker
      io.rancher.container.hostname_override: container_name
